name: wasabi_crossplatform
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # локализация
  flutter_localizations:
    sdk: flutter

  # работа с сетью
  json_annotation: ^4.8.0
  dio: ^5.0.2
  pretty_dio_logger: ^1.3.1

  # архитектура
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

  # кэширование
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0

  # локальное хранение
  shared_preferences: ^2.0.18

  # работа с бд
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.13
  path: ^1.8.2

  # работа с svg
  flutter_svg: ^2.0.4

  # кнопка "Поделиться"
  share_plus: ^6.3.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.5.2

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
  uses-material-design: true